---

version: "3.1"

services:

  web:
    image: "sighup/kubeprimer-web"
    build:
      context: ./web
    environment:
      - "BACKEND_HOST=backend"
    ports:
     - "80:80"
    links:
      - "backend"
    networks:
      - "kubeprimer"

  backend:
    image: "sighup/kubeprimer-backend"
    build:
      context: ./backend
    environment:
      - "MONGO_HOST=mongo"
    links:
      - "mongo"
    networks:
      - "kubeprimer"

  mongo:
    image: "mongo:4.1.5-xenial"
    volumes:
      - "kubeprimer-db:/data/db"
    networks:
      - "kubeprimer"

volumes:
  kubeprimer-db:

networks:
  kubeprimer:
